<?php
/**
 * Fooman_GoogleAnalyticsPlus
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the H&O Commercial License
 * that is bundled with this package in the file LICENSE_HO.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.h-o.nl/license
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to info@h-o.com so we can send you a copy immediately.
 *
 * @category    Fooman
 * @package     Fooman_GoogleAnalyticsPlus
 * @copyright   Copyright © 2012 H&O (http://www.h-o.nl/)
 * @license     H&O Commercial License (http://www.h-o.nl/license)
 * @author      Paul Hachmang – H&O <info@h-o.nl>
 *
 *
 */
/** @var $this Fooman_GoogleAnalyticsPlus_Block_Checkout */
?>

<script type="text/javascript">
    /** GOOGLE ANALTYICS PLUS CHECKOUT TRACKING */

    /* Track step: We track the step when a section in the checkout accordion is openend. */
    Accordion.prototype.openSectionParent = Accordion.prototype.openSection;
    Accordion.prototype.openSection = function(section) {
        Accordion.prototype.openSectionParent.call(this, section);

        try {
            var sectionId = $(section).id;
            var track = '/checkout/onepage/'+sectionId;

            _gaq.push(['_trackPageview', track]);
            <?php if ($this->hasSecondAccount()): ?>
            _gaq.push(['t2._trackPageview', track]);<?php endif; ?>

        } catch(err) {}
    };

    /* Track placeOrder click: This method gets triggered if the ajax call is succesfull on the review step. */
    Review.prototype.nextStepParent = Review.prototype.nextStep;
    Review.prototype.nextStep = function(transport){
        Review.prototype.nextStepParent.call(this, transport);

        try {
            if (this.isSuccess) {
                var track = '/checkout/onepage/opc-review-placeOrderClicked';

                _gaq.push(['_trackPageview', track]);
                <?php if ($this->hasSecondAccount()): ?>
                _gaq.push(['t2._trackPageview', track]);<?php endif; ?>

            }
        } catch(err) {}
    }
</script>