<?php
/**
 * @var $this Fooman_GoogleAnalyticsPlus_Block_GaConversion
 */
if($this->isEnabled()): ?>
<!-- Google Code for <?php echo $this->getLabel() ?> Conversion Page -->
<script type="text/javascript">
//<![CDATA[
var google_conversion_id = <?php echo $this->getConversionId() ?>;
var google_conversion_language = "<?php echo $this->getLanguage() ?>";
var google_conversion_format = "<?php echo $this->getFormat() ?>";
var google_conversion_color = "<?php echo $this->getColor() ?>";
var google_conversion_label = "<?php echo $this->getLabel() ?>";
<?php if ($this->getValue()): ?>
var google_conversion_value = <?php echo $this->getValue(); ?>
<?php endif; ?>
<?php echo "\n"; //for some reason new line was not showing up?>
var google_remarketing_only = false;
//]]>
</script>
<script language="JavaScript" type="text/javascript" src="//www.googleadservices.com/pagead/conversion.js"></script>
<noscript>
    <div style="display:inline;">
        <img height="1" width="1" border="0" alt="" src="//www.googleadservices.com/pagead/conversion/<?php echo $this->getConversionId() ?>/?value=<?php echo $this->getValue() ?>&label=<?php echo $this->getLabel() ?>&guid=ON&script=0">
    </div>
</noscript>
<?php endif; ?>
